import initTranslations from "@/app/i18n";
import TranslationsProvider from "@/components/i18n/TranslationProvider";
import Navbar from "@/components/nav/Navbar";
import ThemeProvider from "@/components/themes/ThemeProvider";
import { Box } from "@/node_modules/@mui/material/index";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Template App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
	const { options } = await initTranslations(locale, ["default"]);

	return (
		<ThemeProvider>
			<html lang="en" suppressHydrationWarning>
				<head />
				<body>
					<TranslationsProvider namespaces={options.ns || "default"} locale={locale}>
						<Navbar locale={locale} />
						<Box component="main">
							{children}
						</Box>
					</TranslationsProvider>
				</body>
			</html>
		</ThemeProvider>
	);
}
