import initTranslations from "@/app/i18n";
import TranslationsProvider from "@/components/i18n/TranslationProvider";
import Navbar from "@/components/nav/Navbar";
import ThemeProvider from "@/components/themes/ThemeProvider";
import { CssBaseline } from "@/node_modules/@mui/material/index";
import { Inter } from "next/font/google";
import "./globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Template App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
	const { options } = await initTranslations(locale, ["default"]);

	return (
		<>
			<CssBaseline />
			<html lang="en" suppressHydrationWarning>
				<head />
				<body>
					<ThemeProvider>
						<TranslationsProvider namespaces={options.ns || "default"} locale={locale}>
							<Navbar locale={locale} />
							{children}
						</TranslationsProvider>
					</ThemeProvider>
				</body>
			</html>
		</>
	);
}
